[package]
name = "road_intersection"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
macroquad = "0.3.24"
throttle_my_fn = "0.2"
parking_lot = "0.11"

r = { package = "rand", version = "0.8" }
